### ISSUE TITLE
Key rollover clarin.phonetik.uni-muenchen.de

### ISSUE THREAD

**Issue by klausj** [clarin-eric/SPF-SPs-metadata#254]
The Shibboleth certificate of the Institute of Phonetics and Speech Processing at LMU Munich expires on Sun, 05 Dec 2021.
I would like to start the key rollover process for the host clarin.phonetik.uni-muenchen.de.

**Comment by klausj** [comment]
Step 1 PR: added "Standby" certificate for key rollover #255

**Comment by andmor-** [comment]
I think this is complete with #258 and [r00046](https://github.com/clarin-eric/SPF-SPs-metadata/releases/tag/r00046). Please reopen if you run into any issue
