### ISSUE TITLE
Corpuscle issue with transient SAML attributes

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/SPF-SPs-metadata#57]
> Hi Dieter,<br>
I am trying to debug this. When running the assertion-consumer, I get the following error message:
<br>

&lt;?xml version="1.0"?&gt;
&lt;urn:Response xmlns:urn="urn:oasis:names:tc:SAML:2.0:protocol" IssueInstant="2018-08-09T07:50:12.967Z" ID="SAMLY2lib_msg_f14bb3bb592fadbff9c85328d5859f6e5c89eb376a6b32eb" Version="2.0" InResponseTo="_3D2F13B40675FA2EF8940060D942C38D"&gt;
 &lt;urn1:Issuer xmlns:urn1="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"&gt;<a href="https://idm.clarin.eu&lt;/urn1:Issuer&gt;" rel="nofollow">https://idm.clarin.eu&lt;/urn1:Issuer&gt;</a> 
 &lt;urn:Status&gt;
 &lt;urn:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/&gt;
 &lt;urn:StatusMessage&gt;There is no identity of the requested 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient' SAML identity format for the authenticated principial.&lt;/urn:StatusMessage&gt;
 &lt;/urn:Status&gt;
&lt;/urn:Response&gt;
<br>
<br>
Perhaps you have an 

**Link:** [Conversation with Lucie Wagner](https://app.intercom.com/a/apps/y2bxzwzv/respond/inbox/all/conversations/17895800043)
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/y2bxzwzv/respond/inbox/all/conversations/17895800043) when this issue is closed.

**Comment by andmor-** [comment]
According to the original Intercom conversation, this issue is now fixed.
